language: "en-CA"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: false
